// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAgent() {
  return window['go']['main']['App']['CancelAgent']();
}

export function CollapseObsoleteFileHistory(arg1, arg2) {
  return window['go']['main']['App']['CollapseObsoleteFileHistory'](arg1, arg2);
}

export function CreateNewConversation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateNewConversation'](arg1, arg2, arg3, arg4);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function GetDirectoryTree(arg1) {
  return window['go']['main']['App']['GetDirectoryTree'](arg1);
}

export function GetFileContent(arg1, arg2) {
  return window['go']['main']['App']['GetFileContent'](arg1, arg2);
}

export function GetModelList() {
  return window['go']['main']['App']['GetModelList']();
}

export function GetOpenWorkspaces() {
  return window['go']['main']['App']['GetOpenWorkspaces']();
}

export function ListConversations(arg1) {
  return window['go']['main']['App']['ListConversations'](arg1);
}

export function LoadConversation(arg1) {
  return window['go']['main']['App']['LoadConversation'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function LoadSpecificConversation(arg1) {
  return window['go']['main']['App']['LoadSpecificConversation'](arg1);
}

export function OpenPathInExplorer(arg1, arg2) {
  return window['go']['main']['App']['OpenPathInExplorer'](arg1, arg2);
}

export function SaveConversation(arg1, arg2) {
  return window['go']['main']['App']['SaveConversation'](arg1, arg2);
}

export function SaveFileContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2, arg3);
}

export function SaveOpenWorkspaces(arg1, arg2) {
  return window['go']['main']['App']['SaveOpenWorkspaces'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function SendUserMessage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SendUserMessage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ToggleModelFavorite(arg1) {
  return window['go']['main']['App']['ToggleModelFavorite'](arg1);
}
