// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelAgent():Promise<void>;

export function CollapseObsoleteFileHistory(arg1:Array<main.ChatMessage>,arg2:string):Promise<Array<main.ChatMessage>>;

export function CreateNewConversation(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.SavedConversation>;

export function DeleteConversation(arg1:string):Promise<void>;

export function GetDirectoryTree(arg1:string):Promise<main.FileNode>;

export function GetFileContent(arg1:string,arg2:string):Promise<string>;

export function GetModelList():Promise<Array<main.ModelItem>>;

export function GetOpenWorkspaces():Promise<main.OpenWorkspacesResult>;

export function ListConversations(arg1:string):Promise<Array<main.SavedConversation>>;

export function LoadConversation(arg1:string):Promise<main.SavedConversation>;

export function LoadSettings():Promise<main.AppSettings>;

export function LoadSpecificConversation(arg1:string):Promise<main.SavedConversation>;

export function SaveConversation(arg1:string,arg2:main.SavedConversation):Promise<void>;

export function SaveFileContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveOpenWorkspaces(arg1:Array<string>,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SelectWorkspace():Promise<string>;

export function SendUserMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function ToggleModelFavorite(arg1:string):Promise<void>;
